name: testing-image

on:
  push:
    branches:
      - main
    paths:
      - example-fn/**

jobs:
  testing-images:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: example-fn
        token: ${{ secrets.PUSH_TOKEN }}
        
    - name: Create an image with Dockerfile
      run: docker build -t image1-fn example-fn/example-fn

    - name: Using a container with the previous image and running the Python script
      run: docker run --name contenedor2-fn -v $(pwd)/example-fn/example-fn/images:/example-fn/images -e FSOURCE='images' image1-fn
      
    - name: Publish results
      if: ${{ steps.check_push_author.outputs.push_author != 'github-actions[bot]@users.noreply.github.com' }}
      run: |
        cd example-fn
        ls
        git config --local user.name "$USERNAME"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Python results"
        git push https://$USERNAME:$REPO_KEY@github.com/AlvaroRodriguezGallardo/src-brokering.git
      env:
        REPO_KEY: ${{ secrets.PUSH_TOKEN }}
        USERNAME: github-actions[bot]
