name: testing-image

on: [push]

jobs:
  testing-images:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: example-fn

    - name: git init
      run: git init
      
    - name: Config
      run: |
          git config user.name "AlvaroRodriguezGallardo"
          git config user.email "alvaro155w@gmail.com"

    - name: Create an image with Dockerfile
      run: docker build -t image1-fn example-fn/example-fn

    - name: Using a container with the previous image and running the Python script
      run: docker run --name contenedor2-fn -v $(pwd)/example-fn/example-fn/images:/example-fn/images -e FSOURCE='images' image1-fn
      
    - name: Copying 'edges' files
      run: find example-fn/example-fn/images -type f -name '*_edges*' -exec cp {} ./ \;

    - name: git tag
      run: git tag

    - name: git branch -M main
      run: git branch -M main

    - name: git tag
      run: git tag
      
    - name: Commiting
      run: | 
          git add *edges*
          git commit -am "Commiting edge files"

    - name: git tag
      run: git tag
          
    - name: Pushing
      run: git push origin main
