name: testing-image

on: [push]

#env:
#        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        
jobs:
  testing-images:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: example-fn
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create an image with Dockerfile
      run: docker build -t image1-fn example-fn/example-fn

    - name: Using a container with the previous image and running the Python script
      run: docker run --name contenedor2-fn -v $(pwd)/example-fn/example-fn/images:/example-fn/images -e FSOURCE='images' image1-fn
      
 #   - name: Copying 'edges' files
  #    run: find example-fn/example-fn/images -type f -name '*_edges*' -exec cp {} ./ \;
      
    - name: Publish results
      env:
            REPO_KEY: ${{ secrets.GITHUB_TOKEN }}
            USERNAME: github-actions[bot]
      run: |
            cd example-fn
            git config --local user.name "$USERNAME"
            git config --local user.email "alvaro155w@gmail.com"
            git add -A
            git commit -m "Python results"
            git push https://$USERNAME:$REPO_KEY@github.com/AlvaroRodriguezGallardo/src-brokering.git
