name: testing-image

on: [push]

jobs:
  testing-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: example-fn

    - name: Create an image with Dockerfile
      run: docker build -t image1-fn example-fn/example-fn

    - name: Using a container with the previous image and running the Python script
      run: docker run --name contenedor2-fn -v $(pwd)/example-fn/example-fn/images:/example-fn/images -e FSOURCE='images' image1-fn

    - name: Cre
      run: git config --global user.name "AlvaroRodriguezGallardo"

    - name: email
      run: git config --global user.email "alvaro155w@gmail.com"

    - name: Cloning repository
      run: git clone git@github.com:AlvaroRodriguezGallardo/src-brokering.git

    - name: List files
      run: ls -R

    - name: Copying generated images within folder 'images'
      run:  find example-fn/example-fn/images -type f -name '*_edges*' -exec cp {} ./ \;
    
    - name: List files
      run: ls -R

    - name: Making changes in repository 'add'
      run: git add *edges*

    - name: Making changes in repository 'commit'
      run: git commit -m

    - name: Making changes in repository 'push'
      run: git push
