name: testing-image

on: [push]

jobs:
  testing-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          path: example-fn
      - name: ls
        run: ls
      - name: Create an image with Dockerfile
        run: docker build -t image1-fn example-fn

      - name: Using a container with the previous image and running the Python script
        run: docker run --name contenedor2-fn -v $(pwd)/example-fn/images:/example-fn/images -e FSOURCE='images' image1-fn
