name: testing-image

on: [push]

jobs:
  testing-images:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: example-fn-logging
    #    path: example-fn
   #     path: example-fn-optimised
        token: ${{ secrets.PUSH_TOKEN }}
        
    - name: Create an image with Dockerfile
      run: docker build -t image1-fn example-fn/example-fn || docker build -t image1-fn example-fn-logging/example-fn-logging || docker build -t image1-fn example-fn-optimised/example-fn-optimised

    - name: Using a container with the previous image and running the Python script
      run: docker run --name contenedor2-fn -v $(pwd)/example-fn/example-fn/images:/example-fn/images -e FSOURCE='images' image1-fn || docker run --name contenedor2-fn -v $(pwd)/example-fn-logging/example-fn-logging/images:/example-fn-logging/images -e FSOURCE='images' image1-fn || docker run --name contenedor2-fn -v $(pwd)/example-fn-optimised/example-fn-optimised/images:/example-fn-optimised/images -e FSOURCE='images' image1-fn
      
 #   - name: Copying 'edges' files
  #    run: find example-fn/example-fn/images -type f -name '*_edges*' -exec cp {} ./ \;
      
    - name: Publish results
      if: ${{ steps.check_push_author.outputs.push_author != '41898282+github-actions[bot]@users.noreply.github.com' }}
      run: |
            cd example-fn || cd example-fn-logging || cd example-fn-optimised
            ls
            git config --local user.name "$USERNAME"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Python results"
            git push https://$USERNAME:$REPO_KEY@github.com/AlvaroRodriguezGallardo/src-brokering.git
      env:
            REPO_KEY: ${{ secrets.PUSH_TOKEN }}
            USERNAME: github-actions[bot]
